REST-API server and client added, timeset capability
relffok/mir_robot pull request #14
Opened 2022-01-19 16:06 UTC by niemsoen

2022-01-20 15:56 UTC, niemsoen commented
This adds 
- the restapi capability (for now only timeset call)

2022-01-26 08:34 UTC, relffok requested changes

2022-01-26 08:34 UTC, relffok commented on mir_restapi/mir_restapi/mir_restapi_server.py
> +            'mir100_setTime',
Let's stick to mir_, so this will be able to support different models too! ROS1 supports mir_100,200,500 so far.

2022-01-26 08:34 UTC, relffok commented on mir_restapi/mir_restapi/mir_restapi_lib.py
> +        tz_str = "Europe/Berlin"
I this necessary? Can it be fetched from the host system?

2022-01-26 08:34 UTC, relffok commented on mir_restapi/mir_restapi/mir_restapi_lib.py
> +    def setDateTime(self):
Might be useful to call it sync time to make sure it's understood that the time is synced to the host system?

2022-01-26 08:34 UTC, relffok commented on mir_driver/mir_driver/mir_bridge.py
> +        restapi_client.set_mir_time()
Yes to launching the RestAPIClient but I don't think it's necessary/useful to sync the time every time the driver is launched. 

If we remove the call and set the time manually after the driver has launched, is a restart of the driver necessary because of emergency stop?

2022-01-26 08:34 UTC, relffok commented on mir_restapi/mir_restapi/mir_restapi_client.py
> +    main()
new line (but will be fixed in a formatting PR soon anyway)

2022-01-26 14:15 UTC, niemsoen commented on mir_restapi/mir_restapi/mir_restapi_lib.py
> +    def setDateTime(self):
I agree, that makes more sense!

2022-01-26 14:17 UTC, niemsoen commented on mir_restapi/mir_restapi/mir_restapi_client.py
> +    main()
Is a new line missing at the end or one too much before if __name__ == '__main__': ?

2022-01-26 14:28 UTC, niemsoen commented on mir_driver/mir_driver/mir_bridge.py
> +        restapi_client.set_mir_time()
I launched the mir_bridge with the restapi-client but without setting the time. Tested /cmd_vel with teleop.
When calling the timesync service after the mir bridge is up and connected, the time is set correctly, however the mir bridge is unresponsive afterwards. It doesn't crash, but it doesn't accept any /cmd_vel anymore. So in that case we need to restart the driver.

2022-01-26 15:06 UTC, niemsoen commented on mir_driver/mir_driver/mir_bridge.py
> +        restapi_client.set_mir_time()
I also tested another API call (get status). If I call that one after the mir bridge is up, hte mir bridge does not freeze but works fine.

2022-01-26 15:20 UTC, niemsoen commented on mir_restapi/mir_restapi/mir_restapi_lib.py
> +        tz_str = "Europe/Berlin"
You're right, there is a simpler solution, I committed it here.

2022-02-02 14:39 UTC, relffok commented
Thanks for the adaptions, could you add a short how-to in the README section where the time synchronization is mentioned?

2022-02-03 09:04 UTC, niemsoen commented
Added the readme section with guide to sync time in ros and removed the automatic time sync call at startup of mir_driver

2022-02-03 09:27 UTC, niemsoen commented
did some housekeeping, now it's ready for merge :)

2022-03-01 14:11 UTC, niemsoen commented
Hey, I resolved the conflicts, that came up recently :)

2022-03-02 10:44 UTC, relffok reviewed
I was finally able to check this on the real robot. Looks good to me! Only minimal comments. Thanks!

2022-03-02 10:44 UTC, relffok commented on mir_driver/mir_driver/mir_bridge.py
> +from mir_restapi.mir_restapi_client import MirRestAPIClient
This is needed anymore since driver is not starting APIClient?

2022-03-02 10:44 UTC, relffok commented on mir_driver/package.xml
> +  <depend>mir_restapi</depend>
can also be removed as a dependency

2022-03-02 10:44 UTC, relffok commented on mir_restapi/package.xml
> +
somehow missed this in the last review but dependecies are missing here!

2022-03-02 10:44 UTC, relffok commented on mir_restapi/mir_restapi/mir_restapi_lib.py
> +                self.logger.info("REST API: Setting time Mir triggers emergency stop, please unlock.")
Lets make this a warn message, so one can easily see it since the GET failed messages afterwards flush the log output

2022-03-02 12:38 UTC, niemsoen commented on mir_driver/mir_driver/mir_bridge.py
> +from mir_restapi.mir_restapi_client import MirRestAPIClient
done with latest merge

2022-03-02 12:49 UTC, niemsoen commented
Okay put requested changes into PR

2022-03-02 12:55 UTC, merged